---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "viseron.fullname" . }}-data
  labels:
    {{- include "viseron.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storage.data.className }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "viseron.fullname" . }}-config
  labels:
    {{- include "viseron.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storage.config.className }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage.config.size }}
